### ISSUE TITLE
[Mechanics] - Test thrower sketch is not fully defined

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#1]
The sketch is missing some constraints and dimensions, that is why it is blue.
![image](https://user-images.githubusercontent.com/5435954/133922348-8ec847dc-e722-4b5d-93af-c664bc1ca0cf.png)
If I were to move a vertex, unexpected things can happen, making it extremely difficult to modify this sketch further. Case and point: When moving one corner vertex this happened.
![image](https://user-images.githubusercontent.com/5435954/133922380-edb95b98-1f14-47ab-b33a-528dd21ef107.png)

**Comment by mbz4** [comment]
ok, will add some dimension pointers to the sketch to reference about origin

**Comment by mbz4** [comment]
made a hot mess of things but it works now: sketch fully defined (i hope, tested a lot)

![image](https://user-images.githubusercontent.com/30321314/134554274-9abe7465-165c-422c-8147-9f45fc329ebd.png)

**Comment by mbz4** [comment]
nevermind, just saw the blue peg hole xD
ok fixed!

**Comment by Akustav** [comment]
Seems to be OK now with the components, yes.
