### ISSUE TITLE
No play at all in roller width

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#102]
Currently there is no play between the roller and the sidewalls. This can stall the motor.

![image](https://user-images.githubusercontent.com/5435954/151010987-1bccbaec-7492-4ea6-9fcf-53d1091bda8e.png)

**Comment by Akustav** [comment]
I also suggest adding a spacer to to the front so someone crashing into your roller does not wreck the thrower. It also adds rigidity to the thrower motor.

**Comment by mbz4** [comment]
Fixed. Adding spacer.

**Comment by mbz4** [comment]
Disregard add spacer - would have to extend adapter plates + the thrower is 3cm further inboard than any robot can reach. It is safe.
