### ISSUE TITLE
Thrower motor cable channel?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#110]
The advanced design does not seem to have a good way for the cables to run into the chassis:

![image](https://user-images.githubusercontent.com/5435954/151033146-1485f928-b5db-47bb-9be0-048f0c9507d5.png)

Compared to the basic design:

![image](https://user-images.githubusercontent.com/5435954/151033206-b5e34dd0-2cbd-4b22-a076-00b50a1307d5.png)

**Comment by Akustav** [comment]
Space wise it compares as follows:
1.8mm vs 4.2 mm

**Comment by mbz4** [comment]
the basic design has 4mm free space irl

**Comment by mbz4** [comment]
just in case, added bit more space

**Comment by Akustav** [comment]
Seems more reasonable now
