### ISSUE TITLE
[Mechanics] - deepen holes

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#12]
I suggest making these holes deeper. Threading tools have a tip that can not be used for cutting and a deeper hole makes for better threads and for more space for shavings to go.

![image](https://user-images.githubusercontent.com/5435954/136580707-73103c1a-ab86-43cd-8ade-101fe0e0c9a6.png)

**Comment by mbz4** [comment]
![image](https://user-images.githubusercontent.com/30321314/136602574-831fe8de-6de5-480f-8f8a-62cd35161eab.png)
Done. Reslicing now.
