### ISSUE TITLE
Code functionality hard to extend

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#17]
https://github.com/ut-robotics/picr21-team-bts/blob/150fad70ade07c8de07883c7dcfbdee1cfe69f68/Mainboard%20Communication%20Tasks/basic.py#L71

The current program is written as a monolith and not expandable. All tasks during the course build on top of the previous tasks. I would therefore suggest a state machine and the first state can be for simple motion forward.

**Comment by Farnaz03** [comment]
Working on it: https://github.com/ut-robotics/picr21-team-bts/tree/main/Programming

**Comment by Akustav** [comment]
Added another issue explaining basic state-machine stuff. Closing this one
