### ISSUE TITLE
Use serial.tools.list_ports

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#18]
https://github.com/ut-robotics/picr21-team-bts/blob/150fad70ade07c8de07883c7dcfbdee1cfe69f68/Mainboard%20Communication%20Tasks/basic.py#L71

Instead of blindly trying to open ports, use [serial.tools.list_ports](https://pyserial.readthedocs.io/en/latest/tools.html) to find the correct port based on the port info.

**Comment by Farnaz03** [comment]
Fixed. Kindly review here: https://github.com/ut-robotics/picr21-team-bts/blob/main/Programming/serial_comms_inator.py
