### ISSUE TITLE
Reduce duplicate code

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#19]
https://github.com/ut-robotics/picr21-team-bts/blob/150fad70ade07c8de07883c7dcfbdee1cfe69f68/Mainboard%20Communication%20Tasks/main2_1.py#L20-L28

Currently motor speed calculations, sending and camera logic is duplicated in multiple files. I would suggest moving common logic to separate files.

**Comment by Farnaz03** [comment]
Working on separating it: https://github.com/ut-robotics/picr21-team-bts/tree/main/Programming
