### ISSUE TITLE
Abstraction layer for motion missing

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#21]
https://github.com/ut-robotics/picr21-team-bts/blob/150fad70ade07c8de07883c7dcfbdee1cfe69f68/Mainboard%20Communication%20Tasks/main2_1.py#L65

The current  motion code sends raw motor speeds to the mainboard. This is a non-intuitive way of moving omnidirectionally and in all likelyhood in need of an abstraction layer.

**Comment by Farnaz03** [comment]
Kindly review: https://github.com/ut-robotics/picr21-team-bts/blob/main/Programming/maneuver_inator.py
Let us know if this works better. We took inspiration from LoganPaul (2020), Thomas The Dunk Engine (2020), Team Kobe (2021), Team Jordan (2021) and also your suggested side, forward, rotate movement structure - but we have so far only implemented a single move command.

**Comment by Akustav** [comment]
Seems more reasonable now.
