### ISSUE TITLE
[Mechanics] - roller number does not divide by fastening holes

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#22]
Currently you have 25 rollers for 4 fastening holes. I would suggest either going with 40 rollers or 5 fastening holes.

**Comment by mbz4** [comment]
Since we are limited to 20 rollers per wheel, it is not possible to go with the 40 rollers option. 
5 fastening holes is a better solution. Guess I will make this solution work then.

**Comment by mbz4** [comment]
![image](https://user-images.githubusercontent.com/30321314/139523987-97faa8dc-f1bc-4dbf-8153-7d443ca56778.png)
Done.

**Comment by Akustav** [comment]
OK
