### ISSUE TITLE
[Mechanics] - motor fastener impossible to lathe

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#23]
All torque related to robot movement will be transferred through the fastening piece. The load is also dynamic since accelerations are quire strong on these pieces. I suggest making it out of metal (aluminum or similar) using the lathe.

**Comment by mbz4** [comment]
![image](https://user-images.githubusercontent.com/30321314/139506856-b248f5d7-55f3-401f-b722-fb36cc922a35.png)
Hey, the adapter piece is made of aluminum: I figured I could use the lathe to get the rough diameter then the mill to mill out the retention hole. Another solution is to simply use the lathe and make a monolith cylinder, with a side where the screw goes through to pin on the shaft of the motor, holes for the wheel screws and of course the hole for the motor shaft - not sure how to make the flat edge in that case but it should work even without it.
In the design, I actually use a flat face on the printed base and lid blocks to help translate the torques but these parts are not meant to work alone in this fashion. I wanted to distribute these loads as much as possible.

I guess I should remake the design to whatever we can fabricate then.
There should be something I can do to simplify this design.

**Comment by mbz4** [comment]
![image](https://user-images.githubusercontent.com/30321314/139524332-92b2b900-a424-4f39-a162-1ae834927016.png)
Perhaps an adapter like this would be better then: 2 separate radii to lathe out, a centre bore for the motor shaft. Then on the mill: 5 vertical screw mount holes  (2.9mm dia), 1 cross-cut horizontal screw hole.

I went with a through cut on the horizontal screw mount in case we want to use part of a threadlocked screw insert as the flat face against which the motor shaft rests and/or as a second retention screw.
In any case it is an optional part that is simply a nice through-mill to fabricate.

**Comment by mbz4** [comment]
I would sand the edges to get the chamfers except for the inner most one which can be achieved if I simply avoid lathing that part to get a nicer transition to the central shaft holder.

**Comment by mbz4** [comment]
![image](https://user-images.githubusercontent.com/30321314/139524444-e443c090-d7be-4262-9e08-621fdb218569.png)

**Comment by Akustav** [comment]
I would use the second variant, yes. One thing I think we can change is to reduce the OD of the holder. This lets us save material and reduce the time of making this piece. The 4/5/however many fastening holes can be pretty close to the edges of the shaft holder and the OD.

One suggestion I can make is that the holes holding the motor shaft should be offset from the wheel fastening holes, like so:

![image](https://user-images.githubusercontent.com/5435954/139579036-7d5f495e-a415-40f9-961f-3589b7d64fb9.png)

This reduces possible assembly complications in the case some the bolts used are too long

**Comment by mbz4** [comment]
Seems the thread here is out of date: I addressed this issue soon after posting the above screenshots. It's angled correctly now, but to achieve this, I had to reposition the fastener holes in order to keep the horizontal retentors aligned with the flat of the motor shaft.

**Comment by mbz4** [comment]
Why is this issue still open?

**Comment by Akustav** [comment]
Current design is better.
