### ISSUE TITLE
[Mechanics] - donät leave play on the motor shaft hole

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#24]
Currently the radius of the motor shaft hole is 3.1 mm. I suggest not leaving any play there.

**Comment by mbz4** [comment]
So you suggest the roller shafts should be immobilized and inside a contour that maximizes friction.

**Comment by mbz4** [comment]
Done: motor shaft hole = 3mm

**Comment by Akustav** [comment]
In what model was this changed?

**Comment by mbz4** [comment]
Both the twin-bore and regular.

**Comment by mbz4** [comment]
Why is this issue open still?

**Comment by Akustav** [comment]
Is OK now
