### ISSUE TITLE
[Mechanics] - Change way how rollers are retained

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#25]
Currently the tolerances for the rollers might be to little and they might not spin freely. To avoid this you can increase side clearance on either side to around 0.2-0.3 mm and extrude a cone like area around the roller shaft that supports the roller from movement. The tolerances on the cone can be right at 4.0mm.

Visual illustrations (not to scale):

![image](https://user-images.githubusercontent.com/5435954/139491399-c6b8baa7-9be1-4b4c-a9db-68b431b05984.png)

An example wheel picture

![image](https://user-images.githubusercontent.com/5435954/139491482-6a54daaf-5f73-4416-9b8c-31070355678d.png)

**Comment by mbz4** [comment]
I can approach this issue by making the hole model for the rollers separate of the hole model for the shafts. I'll therefore define a new sketch on the side of one roller wall and then make a cut and then use the circular pattern on this cut for all the rollers.

**Comment by mbz4** [comment]
Somehow missed the point about the extruded conical shape to keep the roller tight at 4.0mm while permitting play at 0.2-0.3mm in all new designs...
I think I can add it still but this will involve several hundred modifications.
Do you need me to fully assemble the wheels for each iteration or can I leave the non-final versions more disassembled (only 1 or 2 rollers fitted for illustration).
Can fully assemble once we've gone thru feedback I guess.

**Comment by mbz4** [comment]
Okay, fixed for standard config. Tackling twin-bore config next.

![image](https://user-images.githubusercontent.com/30321314/139531286-42c45eea-cbe0-4258-8eb9-f1de9b414a75.png)

**Comment by mbz4** [comment]
![image](https://user-images.githubusercontent.com/30321314/139531303-48ba66f7-8b86-4328-bea5-d640061a0822.png)
It's just a conical extrusion, achieved thru a standard solid join extrude, then chamfered to a nice tip.

**Comment by mbz4** [comment]
![image](https://user-images.githubusercontent.com/30321314/139531564-af1cda9c-18dc-4af4-afb3-49cc7e940713.png)
Done for both wheel configs.
Reviewed all issues again and I think it's all addressed adequately now.
Kindly accept the final design for submission per pending task requirements.

**Comment by Akustav** [comment]
Seems nice now.
