### ISSUE TITLE
Uneven styling in code

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#29]
Code indenting is uneven across the file. It should be unified across the whole project to simplify reading.

https://github.com/ut-robotics/picr21-team-bts/blob/f72089bd664bcdcd6df3d51b7ef4cdaa65b46ecc/Mainboard%20Communication%20Tasks/conBot.c#L16-L47

**Comment by mbz4** [comment]
Reading for whom?

**Comment by Silaris** [comment]
Also got this comment before, will fix
