### ISSUE TITLE
[Mechanics] - Thrower arch is weird

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#3]
I am not sure why the throwers ramp is designed in such a way:
![image](https://user-images.githubusercontent.com/5435954/133923091-0a600fa8-08c7-465e-acab-2b28fc8757a7.png)
The radius is not aligned with the centre of the motor. The ball does not seem to make a lot of contact with the ramp at the beginning of the throw.

Additionally, the ball makes contactwith the motor alot sooner than with the ramp. This can force the robot to jump, reducing accuracy. This happens when the ball is pulled from position one to position 2:
![image](https://user-images.githubusercontent.com/5435954/133923080-6402ab9d-4913-437e-9964-9eebcc80b778.png)

**Comment by mbz4** [comment]
Again, the measurements for motor position are only referenced from last years robot model.
In the given timeframe it was not possible to finetune the design to this degree.
Additionally, the ramp geometry is comprised out of two concentric circles, the motor axis is indeed not in the central axis mount as it should be. The draft angle between both ramp curves serves as the simplest self-centering geometry I could quickly implement.
One solution may be that I move the motor mount up a few mm such that the 'jump' would not occur, assuming the carpet is as depicted.

**Comment by Akustav** [comment]
I think you should align the centre of the motor with the ramps curvature centre. Since you have full control of where the motor is located then you can also decide how far the ramp extends, helping avoid the issue where the robot is lifted during ball acquisition.

Using pro-paint skills I have illustrated some changed that would be nice:
![image](https://user-images.githubusercontent.com/5435954/133932475-c15c9be9-512b-440d-ab78-cb1448a7b4f1.png)

**Comment by Akustav** [comment]
Hey! Still a little bug here: 
![image](https://user-images.githubusercontent.com/5435954/134944755-bd1a2f74-7c1c-42ae-92fd-fdaf1112ec02.png)

**Comment by Akustav** [comment]
Closing due to new design
