### ISSUE TITLE
Uneven casing in python code

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#32]
As was the case with C code so should python code be unified under one standard. Currently you have multiple syntaxes mixed.

https://github.com/ut-robotics/picr21-team-bts/blob/f72089bd664bcdcd6df3d51b7ef4cdaa65b46ecc/Mainboard%20Communication%20Tasks/motionModule.py#L29

https://github.com/ut-robotics/picr21-team-bts/blob/f72089bd664bcdcd6df3d51b7ef4cdaa65b46ecc/Mainboard%20Communication%20Tasks/motionModule.py#L47

**Comment by mbz4** [comment]
What's the problem with that?

**Comment by Akustav** [comment]
You use camelCase and snake_case at the same time. You should decide on one and use it.

**Comment by Silaris** [comment]
Got you. It was 2 programmer code combination and we are using different styles D Will change
