### ISSUE TITLE
Motor speeds should be defined programatically

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#33]
The current way how motor speeds are defined is weird is as in the user needs to provide input before it starts. This is pretty useless as code evolves. It would be more reasonable to define a set speed/direction inside code and drive based on that.

https://github.com/ut-robotics/picr21-team-bts/blob/f72089bd664bcdcd6df3d51b7ef4cdaa65b46ecc/Mainboard%20Communication%20Tasks/base.py#L14-L23

**Comment by mbz4** [comment]
It is useless to whoever tries to use it apart from the guy ACTUALLY building the bot who just needs to access those few variables. Again, how did this get here in main commit?

**Comment by Akustav** [comment]
I am not sure how this code got here but it is very narrow in scope and is unusable further in the project, therefore of low quality.

**Comment by Silaris** [comment]
base3.py (current version) does not include this input. It is just for playing.

**Comment by Akustav** [comment]
There are currently quite a few baseX.py files. Maybe it is reasonable to clean this up to have one base?

**Comment by Silaris** [comment]
Will clean them up with a new camera controller. Now it is stored in base2.py with cv only and base3.py with realsense (faster to program in 1 file for test purposes)

**Comment by Akustav** [comment]
Okay. I would use either folders to designate test code or keep them in a separate branch, else it can be difficult to understand what generically named files like base1, base2 and similar are supposed to do
