### ISSUE TITLE
What is the purpose of this bit here in motionModule.py?

### ISSUE THREAD

**Issue by mbz4** [ut-robotics/picr21-team-bts#34]
![image](https://user-images.githubusercontent.com/30321314/139834558-acfbd5e3-2687-44b4-a197-3959c76e7bae.png)

**Comment by mbz4** [comment]
![image](https://user-images.githubusercontent.com/30321314/139834768-2e5f0cd3-5de6-43cf-a567-1b9eaadacf09.png)

**Comment by mbz4** [comment]
![image](https://user-images.githubusercontent.com/30321314/139834845-e7e8e1d8-fc3a-4a24-9540-d71cb9942786.png)

**Comment by Silaris** [comment]
Junk, was testing random things. Already removed it in the current version. Will be removed in next commit
