### ISSUE TITLE
[Mechanics] - change way roller shafts are retained

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#35]
I would suggest changing the way how rollers sit inside the wheel housing. Currently you have 2 semicircles that enclose the shaft but you can encounter alignment issues due to the more complex matching between 2 moving semi-circles.

I would suggest a slot that is as deep as the shafts diameter and a flat surface retains this shaft in the housing.

A picture to illustrate:
![image](https://user-images.githubusercontent.com/5435954/139918144-97e4c2e6-9afe-4f70-bca8-808e98af8bda.png)

**Comment by mbz4** [comment]
Thank you for the suggestion, I will implement it because there are too many misalignment opportunities that could cause this. It may be possible to have a shape on the locking block to enclose them fully but that might again be asking for trouble.

**Comment by mbz4** [comment]
I'll make a new design for the twin-bore that has a unibody mid section like your proposed solution.

**Comment by Akustav** [comment]
Let me know when ready

**Comment by mbz4** [comment]
Done!

**Comment by Akustav** [comment]
OK
