### ISSUE TITLE
[Mechanics] - countersink style

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#36]
Was wondering you you plan to use this style of countersink head or want to use, for example, a conical head?
![image](https://user-images.githubusercontent.com/5435954/139919847-cdfb5bbd-ce42-42d0-97dd-eb85dc9d99a6.png)

**Comment by mbz4** [comment]
We discussed this issue previously and in person: it would need 5 torx conical screws, ~30mm each. None are in stock at this length so for the twin-bore it is out of the question. We could apply them however to the regular wheel instead.

**Comment by Akustav** [comment]
I think we can get the screws. Do I understand correctly that you want to use the twin-design?

**Comment by mbz4** [comment]
We discussed that it would not be a problem if we keep both. But yeah, for now the ideal focus is to use the twin-bore (unibody) design.
The standard wheel design serves as backup in case the configuration misbehaves or something about movement dynamics...

**Comment by mbz4** [comment]
If you are getting the torx screws, let me know their exact dimensions so I can model them in to test the fittings. I don't believe we have a problem in using either design, despite the 'ugly' counterbores.

**Comment by Akustav** [comment]
https://www.tme.eu/en/details/b3x25_bn20039/bolts/bossard/3183910/ This would be a screw

**Comment by Akustav** [comment]
I will close this task for now, I think the overall point was made.
