### ISSUE TITLE
[Mechanics] - drill through fastener if possible to simplify threading

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#37]
I suggest threading through the wheel shaft mount to simplify threading:
![image](https://user-images.githubusercontent.com/5435954/139919933-531bcb43-c612-4105-a95f-4b1fbd7b000d.png)
Seems like one hole is harder to do since it collides with the crossing hole. Does it need a full-length hole?

**Comment by mbz4** [comment]
From memory, I think they only need 2-3 mm, ~1mm short of the horizontal shaft fastener. We also discussed dropping down to 4 fasteners in this adapter case. That would resolve the collision issues as well as slightly reduce weight and complexity.
I want to use this adapter for the regular wheel configuration as well, despite the short displacement of fasteners from motor shaft.

**Comment by mbz4** [comment]
Done!

**Comment by Akustav** [comment]
OK
