### ISSUE TITLE
[Mechanics] - wheel bearing support lips may be too long

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#39]
The extended lips can be shortened to stop potential interference with the bearing. The bearing has some play in it and when extending this lip more than the center it can make contact with the rolling part.

![image](https://user-images.githubusercontent.com/5435954/140605607-58d949bd-3910-4205-93fe-df94cc1959fc.png)

![image](https://user-images.githubusercontent.com/5435954/140605624-6e8105ba-352d-419e-ac9f-2e6d2f0dd382.png)

**Comment by mbz4** [comment]
Fixed on unibody twin-bore.
