### ISSUE TITLE
[Mechanics] - Thrower missing chassis assembly

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#5]
The thrower assembly does not include chassis components, making it hard to judge the distances between the motor and the ground of the machine. Additionally it is hard to judge if it is attachable to the existing test-chassis.

**Comment by mbz4** [comment]
Instructions did not mention the assembly needs to include chassis parts even though I referenced all dimensions from model and real parts. 
These seem like superficial issues but I will add them to the model.
The bottom most face of the ramp component is exactly on level with last years ramp bottom.

**Comment by Akustav** [comment]
Having the chassis in the model helps to see that. Since these components do not work in a vacuum but need to operate in an assembly it is important to see that everything fits together and operates as expected.
