### ISSUE TITLE
Hardcoded ID value

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#57]
Current code has a hardcoded ID value in multiple places. The competition might not use your robots hardcoded ID for it. Changing it can be error prone. I suggest either having it as a separate input variable or define it in the top of the module and reference that constant.

https://github.com/ut-robotics/picr21-team-bts/blob/c1d9243da79889edd1263d32d90fceefeffa7f66/BTS%20dev/ws_client.py#L22-L38

**Comment by Silaris** [comment]
Moved to cycle. Bts is now a parameter in the shared data. (most likely will need to move it to the config file but it is not important now)
