### ISSUE TITLE
Confusing ball choosing

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#59]
What is the logic behind this? You check if there are balls visible, then  you get the coordinates and the distance of the first ball. After that you start to iterate over the balls and update the distance/coordinates of the ball? I think the image processor already returns a sorted list of balls. You should handle filtering there, not in two separate places.

https://github.com/ut-robotics/picr21-team-bts/blob/c1d9243da79889edd1263d32d90fceefeffa7f66/BTS%20dev/see_everything_inator.py#L158-L166

**Comment by Silaris** [comment]
Removed 2nd ball choosing function. Uses native function. It has border processing behind to eliminate balls, not in the court. For the closest ball distance, both x and y are now important. It helps to make decisions faster.
