### ISSUE TITLE
Robot is at an angle in the assembly

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-bts#61]
Better for future work if the robot plates were parallel with the floor.
![Fusion360_2022-01-12_13-07-19](https://user-images.githubusercontent.com/32770145/149129125-63b95459-899e-40a1-a545-162b85c08bc1.png)

**Comment by mbz4** [comment]
fixed!
used inspect tool and checked offset from origin top plane to get difference to zero for bottom chassis part
