### ISSUE TITLE
Camera mount - recessed bolt holes

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-bts#63]
I think it might be structurally better to not have these holes recessed.
![Fusion360_2022-01-12_12-39-23](https://user-images.githubusercontent.com/32770145/149130600-e8e8e6e9-0194-4c68-9f12-1a25c008382d.png)

**Comment by mbz4** [comment]
fixed!
made new gantry mounts for the camera adapter with adequate space for the camera itself
