### ISSUE TITLE
Camera mount - RGB camera position not in center

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-bts#64]
The RGB sensor of the D435 is located on the opposite side of the USB port.
![Fusion360_2022-01-12_13-21-15](https://user-images.githubusercontent.com/32770145/149131006-bdc1c4a8-0fbf-4b14-8924-c61f2730816f.png)

Use the "Intel RealSense Depth Camera D435" from here: https://dev.intelrealsense.com/docs/cad-files
There download should give a STEP file, that can be uploaded to your project in Fusion360.
The model has the position for the RGB camera.

To get the RGB camera to the center of the robot, depending on the design, you might have to have the camera extend outside of the camera mount, and might need to make a cut-out for it.

![Fusion360_2022-01-12_13-02-19](https://user-images.githubusercontent.com/32770145/149131606-d7ec57f3-128d-4e24-909f-ac5f70c6d766.png)

**Comment by mbz4** [comment]
done:
got new model
uploaded model
aligned model
repositioned mounting holes to match
camera aligned to centre of bot
