### ISSUE TITLE
Clearance issues with tenons

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-bts#71]
Check over all of the colored parts. Can cause fitting issues.
![Fusion360_2022-01-16_14-38-46](https://user-images.githubusercontent.com/32770145/149660917-b05fb354-203d-489f-9ccc-4a43e958b7bf.png)

**Comment by mbz4** [comment]
The motor mounts have a 0.05mm margin.
The Gantry features no margin - should I add the 0.05 to gantry mounts?

**Comment by maidlam** [comment]
1. Motor mounts
The motor mounts holes are different dimensions - the tenons are 17,5mm, while their corresponding holes are 17,475mm wide. That is causing the interference there.
![Fusion360_2022-01-16_16-54-22](https://user-images.githubusercontent.com/32770145/149665285-0ec5ae06-9dae-4acb-9d09-44f4dc875414.png)
![Fusion360_2022-01-16_16-55-11](https://user-images.githubusercontent.com/32770145/149665289-26723e91-279d-4a47-86eb-593987c490d7.png)

2. Gantry
The holes for the gantry don't need a margin, but the holes for the tenons are also out of alignment.
![Fusion360_2022-01-16_16-52-43](https://user-images.githubusercontent.com/32770145/149665320-6131c58d-d800-4560-a183-cdb0f7ad5025.png)

**Comment by mbz4** [comment]
Motor mounts:
fixed on top chassis, removed clearance margin on bottom chassis (mounts remain fixed more often than on top chassis)
Gantry:
cannot identify where the misalignment occurred
Perhaps its a bad joint?

**Comment by mbz4** [comment]
Joint is sound. Still cannot find cause for misalignment nor did I find any misalignment.

**Comment by mbz4** [comment]
Fixed gantry assembly misalignment source.
To be sure, I extended the gantry to 118mm internal distance, applied to top and bottom chassis as well (battery cradle mounts had to be offset)

**Comment by maidlam** [comment]
Still some issues with the bottom tenons of all the motor holders. The distance between the holes in the bottom plate is slightly bigger than the distance between the tenons.
Also, one of the holes in the top plate is missing.
![Fusion360_2022-01-16_20-18-17](https://user-images.githubusercontent.com/32770145/149672818-56861a6c-55c1-4fa5-ae8f-5af6787eefd8.png)
