### ISSUE TITLE
Thrower sidewalls could be milled out

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-bts#72]
Are the thrower sidewalls going to be brand new?
If not, then they could be milled out instead.

The current wall dimensions in the model seem to support that, and since the most of the robot is being milled out, these could also be milled out
The distance disk from the wall to the thrower motor would be printed separately.
![Fusion360_2022-01-16_14-45-03](https://user-images.githubusercontent.com/32770145/149661086-7b8f7fca-f5b7-4b0f-a253-fe940259b3a3.png)

**Comment by mbz4** [comment]
The thrower design is actually not up for review as that task was already reviewed. A new thrower will be developed next week and so I just fit this one with an additional cut to serve as a visual stand-in.  To fit LoganPaul's test thrower we currently use, I will simply saw-off 7.6mm off the front part, sand it and then fit it into the new chassis. The advanced thrower will likely have to be milled and not printed but the design does not yet exist.
