### ISSUE TITLE
Remove tabs to increase ease of assembly

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#74]
For ease of assembly I suggest to remove the tabs on the back plate of the motor boxes. Otherwise a high level of precision is needed to attach the motors to the board and the top plate to the rest of the robot. Area is circled in red.

Additionally, you could technically skip the back- and sidewalls entirely. This reduces your mill, finishing and assembly processes. Your call.

![image](https://user-images.githubusercontent.com/5435954/149758245-f5996b34-ba17-4f69-8739-83ea322e5dff.png)

**Comment by mbz4** [comment]
thought it would help keep the mounts stable and reduce play during motion
also i like the design and spent quite some time on it
i agree on removing the top rear tab tho, it's really not needed
but i want to keep the side walls and back brace models just because :)

**Comment by mbz4** [comment]
removed the top tab on the rear brace and the top chassis

![image](https://user-images.githubusercontent.com/30321314/149771181-a7a52757-6d8f-4cad-9fee-7667e3494589.png)
lamenting the fact the bottom chassis looks kinda like a butt now xD
