### ISSUE TITLE
To different methods to solve the same problem in aim

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#82]
https://github.com/ut-robotics/picr21-team-bts/blob/09e9488ed37ca8907c14233833fe658abc6a5cc7/BTS%20dev/game_logician_inator.py#L211

Why have the delay here? You are throwing for 40 frames times 0.05 seconds? The cameras framerate is at most 60, so every iteration has at least 16 ms of delay in it. Why not just increase the iteration number?

**Comment by Silaris** [comment]
Parallel. We do not wait for the camera frame anymore. But this function will be adjusted letter. We haven't updated the throwing algorithm yet.

**Comment by Silaris** [comment]
Updated throw method to additional aiming during the throw. Time. sleep remains. Reduced it to remove the delay.

**Comment by ReikoR** [comment]
In general it seems sort of inefficient way to do it. Not sure if there is any benefit right now in running game logic more frequently than camera framerate. For minimum delay it would be better to run everything after new camera frames are received.
