### ISSUE TITLE
Alot of duplicate code

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#89]
https://github.com/ut-robotics/picr21-team-bts/blob/3a1b7eb9764ac2e18287abd240885eefb3a9ea52/BTS%20dev/rc_inator.py#L42-L96

This code can be simplified so in the if-else statements you set a desired speeds and send it after the if-else block. This reduces a lot of duplicate code.

**Comment by Silaris** [comment]
This section fixed

**Comment by Akustav** [comment]
Seems better now
