### ISSUE TITLE
Internal ramp thickness 5 instead of 4.8

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#93]
The ramp thickness should be 4.8. Currently it is 5.0.

![image](https://user-images.githubusercontent.com/5435954/151006852-131a6908-ea3a-4a6b-94db-3563b6783d6d.png)

Additionally no dogbones:

![image](https://user-images.githubusercontent.com/5435954/151007009-1c95a3a9-8059-4eb1-927b-79df6187e63e.png)

**Comment by mbz4** [comment]
No official requirement for material thickness or material choice. Closing with comment.
