### ISSUE TITLE
Spacer question

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#94]
Will all spacers be F-F?

How to you plan to assemble everything here?

If some of them are F-M, then the threaded part most likely does not pass through 5mm, let alone 4.8mm

![image](https://user-images.githubusercontent.com/5435954/151007323-ee53d098-866f-401c-8b8a-806ec207ab39.png)

**Comment by mbz4** [comment]
Does not matter, can be adjusted in post. Closing.
