### ISSUE TITLE
Weird angle adjustment system

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#95]
. I would suggest having a separate bolt that slides in a similar arm that you have. It can be a little more offset from the ramp arms so it should not create too much interference.

The current solution has a lot of play and does not seem to be too elegant.

![image](https://user-images.githubusercontent.com/5435954/151008868-fe21e280-3bdf-4a60-a972-287c91baf69e.png)

**Comment by mbz4** [comment]
It is a functional design with lots of faults. So is the government. Closing with comment.

**Comment by Akustav** [comment]
Re-opened issue due to there being no solution. Movement of the ramp is the core functionality and needs to work, else it might as well not exist.

**Comment by mbz4** [comment]
fixed, added 3rd bolt

**Comment by mbz4** [comment]
![image](https://user-images.githubusercontent.com/30321314/151041625-60f7468b-4a79-423c-bcb6-d051d90ad1c3.png)
bolt length irrelevant, this works as you wanted
assign points - last call
