### ISSUE TITLE
WAY too tight tolerance on movable ramp slot

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-bts#96]
This slot is exactly 3mm in diameter. This is WAY too tight and will most likely jam. There should be at least 1mm of play

![image](https://user-images.githubusercontent.com/5435954/151009558-4983f596-45ce-4bf3-b05c-db7dca252e63.png)

**Comment by mbz4** [comment]
Agreed, adjusting to 5mm.

**Comment by mbz4** [comment]
Done.
